"""initial migration

Revision ID: 205b4ad42ba9
Revises: 
Create Date: 2025-08-03 18:09:24.422890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205b4ad42ba9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('email', sa.String(length=100), unique=True, index=True, nullable=False),
        sa.Column('username', sa.String(length=100), unique=True, index=True, nullable=False),
        sa.Column('hashed_password', sa.String(length=100), nullable=False),
        sa.Column('full_name', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('is_admin', sa.Boolean(), default=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
