"""Add e-commerce models and update user model

Revision ID: 6235c6122bf8
Revises: c9af9634126e
Create Date: 2025-08-05 09:59:33.074961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6235c6122bf8'
down_revision = 'c9af9634126e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
